services:
  api:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: pnpm run start:dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      # Variables de entorno para el scraper SII
      - RUT_TRIBUTARIO=${RUT_TRIBUTARIO}
      - PASS_TRIBUTARIO=${PASS_TRIBUTARIO}
      - TOKEN_BROWSLESS=${TOKEN_BROWSLESS}